version: 3.4
services:
  workeur_db:
    container_name: workeur_db
    image: postgres
    environment: 
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PGDATA=/data/postgres
    volumes:
      pgdata:/data/postgres
    ports:
      - 5432:5432

volumes:
  pgdata:
    external: true